CREATE SCHEMA tdb;

CREATE TABLE tdb.GAME
(
    GAME_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    HOME_PLAYER VARCHAR(50) NOT NULL,
    AWAY_PLAYER VARCHAR(50) NOT NULL,
    HOME_GOALS INT DEFAULT 0 NOT NULL,
    AWAY_GOALS INT DEFAULT 0 NOT NULL,
    EXTRA_TIME VARCHAR(1) DEFAULT 'N' NOT NULL,
    HOME_PENS INT DEFAULT 0 NOT NULL,
    AWAY_PENS INT DEFAULT 0 NOT NULL,
    WINNER VARCHAR(50) NOT NULL,
    TOURNAMENT_ID INT NOT NULL,
    KNOCK_OUT VARCHAR(1) DEFAULT 'N' NOT NULL
);
CREATE TABLE tdb.PLAYER
(
    NAME VARCHAR(50) PRIMARY KEY NOT NULL
);
CREATE TABLE tdb.TOURNAMENT
(
    TOURNAMENT_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    TOURNAMENT_NAME VARCHAR(50) NOT NULL,
    TOURNAMENT_WINNER VARCHAR(50) NOT NULL,
    WOODEN_SPOON VARCHAR(50) NOT NULL,
    GOLDEN_BOOT VARCHAR(50),
    GOLDEN_BOOT_GOALS INT
);
ALTER TABLE tdb.GAME ADD FOREIGN KEY (WINNER) REFERENCES tdb.PLAYER (NAME);
ALTER TABLE tdb.GAME ADD FOREIGN KEY (AWAY_PLAYER) REFERENCES tdb.PLAYER (NAME);
ALTER TABLE tdb.GAME ADD FOREIGN KEY (HOME_PLAYER) REFERENCES tdb.PLAYER (NAME);
ALTER TABLE tdb.GAME ADD FOREIGN KEY (TOURNAMENT_ID) REFERENCES tdb.TOURNAMENT (TOURNAMENT_ID);
ALTER TABLE tdb.TOURNAMENT ADD FOREIGN KEY (WOODEN_SPOON) REFERENCES tdb.PLAYER (NAME);
ALTER TABLE tdb.TOURNAMENT ADD FOREIGN KEY (GOLDEN_BOOT) REFERENCES tdb.PLAYER (NAME);
ALTER TABLE tdb.TOURNAMENT ADD FOREIGN KEY (TOURNAMENT_WINNER) REFERENCES tdb.PLAYER (NAME);
