SET SCHEMA TDB;
CREATE TABLE COUNTRIES
(
  COUNTRY   VARCHAR(50) NOT NULL
);

INSERT INTO TDB.COUNTRIES
    VALUES ('Argentina')
      ,('Australia')
      ,('Austria')
      ,('Belgium')
      ,('Bolivia')
      ,('Brazil')
      ,('Bulgaria')
      ,('Cameroon')
      ,('Chile')
      ,('Colombia')
      ,('Ivory Coast')
      ,('Czech Republic')
      ,('Denmark')
      ,('Ecuador')
      ,('Egypt')
      ,('England')
      ,('Finland')
      ,('France')
      ,('Germany')
      ,('Greece')
      ,('Hungary')
      ,('India')
      ,('Republic of Ireland')
      ,('Italy')
      ,('Mexico')
      ,('Korea Republic')
      ,('Holland')
      ,('New Zealand')
      ,('Northern Ireland')
      ,('Norway')
      ,('Paraguay')
      ,('Peru')
      ,('Poland')
      ,('Portugal')
      ,('Romania')
      ,('Russia')
      ,('Scotland')
      ,('Slovenia')
      ,('South Africa')
      ,('Spain')
      ,('Sweden')
      ,('Switzerland')
      ,('Turkey')
      ,('United States')
      ,('Uruguay')
      ,('Venezuela')
      ,('Wales');
