SET SCHEMA TDB;
CREATE TABLE PLAYER
(
  NAME               VARCHAR(50) PRIMARY KEY NOT NULL,
  CREATE_DATETIME    TIMESTAMP,
  UPDATE_DATETIME    TIMESTAMP,
  CREATED_BY_USER_ID VARCHAR(30),
  UPDATED_BY_USER_ID VARCHAR(30)
);
